version: '3.4'
services:
  hello_world:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: none
    restart: "no"

